export const colleges = [
    "Harvard University",
    "Stanford University",
    "Massachusetts Institute of Technology (MIT)",
    "Yale University",
    "Princeton University",
    "California Institute of Technology (Caltech)",
    "Columbia University",
    "University of Chicago",
    "University of Pennsylvania",
    "Cornell University",
    "Johns Hopkins University",
    "University of California, Berkeley",
    "University of California, Los Angeles (UCLA)",
    "Duke University",
    "Northwestern University",
    "University of Michigan, Ann Arbor",
    "University of Virginia",
    "Brown University",
    "Dartmouth College",
    "Rice University",
    "University of Notre Dame",
    "Vanderbilt University",
    "Washington University in St. Louis",
    "Emory University",
    "Georgetown University",
    "University of Southern California (USC)",
    "Carnegie Mellon University",
    "University of North Carolina at Chapel Hill",
    "Tufts University",
    "University of Rochester",
    "University of California, San Diego (UCSD)",
    "University of Florida",
    "University of Miami",
    "Wake Forest University",
    "Boston College",
    "Brandeis University",
    "University of Washington",
    "New York University (NYU)",
    "Tulane University",
    "University of Texas at Austin",
    "University of Wisconsin-Madison",
    "University of Illinois at Urbana-Champaign",
    "Georgia Institute of Technology",
    "University of Maryland, College Park",
    "University of California, Davis",
    "University of California, Santa Barbara (UCSB)",
    "Boston University",
    "Northeastern University",
    "Purdue University",
    "University of Minnesota, Twin Cities",
    "University of Pittsburgh",
    "Rutgers, The State University of New Jersey",
    "Arizona State University",
    "Indiana University Bloomington",
    "University of Iowa",
    "University of Georgia",
    "University of Connecticut",
    "Texas A&M University",
    "Michigan State University",
    "Iowa State University",
    "Ohio State University",
    "University of Arizona",
    "University of Colorado Boulder",
    "University of Oregon",
    "University of Utah",
    "Virginia Tech",
    "Florida State University",
    "University of South Carolina",
    "University of Kentucky",
    "University of Oklahoma",
    "University of Kansas",
    "Syracuse University",
    "Temple University",
    "Baylor University",
    "University of Houston",
    "Rensselaer Polytechnic Institute",
    "Colorado State University",
    "Oregon State University",
    "San Diego State University",
    "University at Buffalo (SUNY)",
    "University of Central Florida",
    "University of Cincinnati",
    "University of New Mexico",
    "Kansas State University",
    "Oklahoma State University",
    "University of Delaware",
]
